### PR TITLE
Fix `Ndmsg` struct

### LINKED ISSUE #56: Neighbor table struct (Ndmsg) is broken
The neighbor table struct `Ndmsg` in rtnl.rs is broken:

 * Rtattrs and rta_type for this is missing
 * Padding is missing from (de)serializing
 * Size calculation is wrong due to above

I have been working to fix it (see https://github.com/oherrala/neli/compare/fix-54...oherrala:add-neigh-rtattrs) and it can currently at least deserialize the response from netlink socket, but it's currently on top of #55 and needs to be fixed to be compatible with current master.

### PR DESCRIPTION
**Pull request by oherrala**
As documented in #56, `Ndmsg` struct is broken. This PR fixes it by adding the missing `rtattr` field for the struct, add the missing `rta_type` for `Rtattr`s as well as fixing the alignment of the struct with correct padding. Finally of course fixing the length calculations.

I couldn't find any docs (or use case) for `Ndmsg.ndm_type`, so I changed it to `u8`. It's there, but no idea what it should be used for.

Fixes #56

### CODE REVIEW

**Comment by jbaublitz** [comment]
@oherrala I'm going to request leaving `.ndm_type` as is based on some source code that uses the type I specified. I didn't see any documentation but apparently `RTN_*` constants are valid per [this code](https://github.com/FRRouting/frr/blob/master/nhrpd/netlink_arp.c#L47).

File: src/rtnl.rs [hunk 1]
```diff
@@ -462,12 +462,16 @@ pub struct Ndmsg {
     /// Flags for entry
     pub ndm_flags: Vec<Ntf>,
     /// Type of entry
-    pub ndm_type: Rtn,
+    pub ndm_type: u8,
```
Comment (jbaublitz) [inline src/rtnl.rs]: Please change this back to `Rtn`.

**Comment by oherrala** [comment]
@jbaublitz I think you are right. I did more research and found for example this Linux patch:

  https://lore.kernel.org/patchwork/patch/487044/

which was merged and it confirms the usage of `RTN_` in `ndm_type`. I'll fix my PR.

The funny thing is that the latest `rtnetlink.7` manpage doesn't document `ndm_type` (as seen here http://man7.org/linux/man-pages/man7/rtnetlink.7.html), but there still exist some old version of man page (for example http://www.skrenta.com/rt/man/rtnetlink.4.html) which document it:

> Valid ndm_type values are: NDA_UNSPEC  for  unknown  type, NDA_DST  for  a  neighbour cache network layer destination address,  ND_LLADDR  for  a  neighbour  cache  link  layer address,  ND_CACHEINFO  for  cache  statistics  (a  struct nda_cacheinfo  header   follows).

However, the current Git project of man-pages project doesn't contain the change to remove this part of documentation so it has happened before 1.70 man-pages release (that's where the current Git repo starts: https://github.com/mkerrisk/man-pages/commit/fea681dafb1363a154b7fc6d59baa83d2a9ebc5c).

I filed a bug into Linux's bugzilla: https://bugzilla.kernel.org/show_bug.cgi?id=205345

Maybe the documentation can be improved.
